### ISSUE TITLE
Executing order as shown in example throws error

### ISSUE THREAD

**Issue by maxhq** [bitfinexcom/bitfinex-terminal#19]
When I follow the example in https://github.com/bitfinexcom/bitfinex-terminal/blob/master/examples/exec-strategy.js and the order gets executed, I always receive this error after the `Submitting order {...}` output:
```
node:events:353
      throw er; // Unhandled 'error' event
      ^

Error: Writable stream closed prematurely
    at Pipeline.done (/prj/js-bitfinex/.yarn/cache/streamx-npm-2.10.0-a6072366d6-37df14152a.zip/node_modules/streamx/index.js:393:43)
    at FilterCandles.emit (node:events:388:22)
    at emitCloseNT (node:internal/streams/destroy:169:10)
    at processTicksAndRejections (node:internal/process/task_queues:79:21)
Emitted 'error' event on Readable instance at:
    at ReadableState.afterDestroy (/prj/js-bitfinex/.yarn/cache/streamx-npm-2.10.0-a6072366d6-37df14152a.zip/node_modules/streamx/index.js:439:19)
    at Readable._destroy (/prj/js-bitfinex/.yarn/cache/streamx-npm-2.10.0-a6072366d6-37df14152a.zip/node_modules/streamx/index.js:532:5)
    at ReadableState.updateNonPrimary (/prj/js-bitfinex/.yarn/cache/streamx-npm-2.10.0-a6072366d6-37df14152a.zip/node_modules/streamx/index.js:346:16)
    at ReadableState.update (/prj/js-bitfinex/.yarn/cache/streamx-npm-2.10.0-a6072366d6-37df14152a.zip/node_modules/streamx/index.js:330:69)
    at ReadableState.afterRead (/prj/js-bitfinex/.yarn/cache/streamx-npm-2.10.0-a6072366d6-37df14152a.zip/node_modules/streamx/index.js:469:58)
    at processTicksAndRejections (node:internal/process/task_queues:79:21)
```
Where can I start to investigate?

**Comment by maxhq** [comment]
After some tests with `process.env.DEBUG = 'bfx*'` and an error handler, i.e.
```javascript
for await (const data of stream) {
  const { key, value } = data
  await exec(key, value).catch(e => console.error(error))
}
```
I can see two things:

1. the order is sent:
   ```
    bfx:ws2 sending [0,"on",null,{"cid":1613003299555,"symbol":"tBTCUSD","type":"EXCHANGE MARKET","amount":"0.00033499","flags":0,"meta":{},"price":"44778"}] +42ms
    bfx:ws2 recv msg: [0,"n",[1613003299,"on-req",null,null,[58427416599,null,1613003299555,"tBTCUSD",1613003299580,1613003299580,0.00033499,0.00033499,"EXCHANGE MARKET",null,null,null,0,"ACTIVE",null,null,44778,0,0,0,null,null,null,0,0,null,null,null,"API>BFX",null,null,null],null,"SUCCESS","Submitting exchange market buy order for 0.00033499 BTC."]] +44ms
    ```
2. an error is thrown by `bfx-hf-strategy/lib/orders/trade_for_order.js`:
   ```
   Error: order not fully filled, refusing to create trade (0.00033499/0.00033499)
   ```
According to the `bfx:ws2` debug messages the order is filled later on. But obviously the line `o = await submitOrder(state, orderParams)` in [submit_trade.js](https://github.com/bitfinexcom/bfx-hf-strategy/blob/0d121ef6f7bd47e62d2a1e15123b8affd6f9a6af/lib/orders/submit_trade.js#L32) does not wait till the API says it's filled.
Is this intended behaviour?

**Comment by maxhq** [comment]
Sorry for the spam: it was a layer 8 problem:)
I assumed the sample `submitOrder()` function would also work with `simulateFill: false` - my mistake.
Nevertheless the `.catch()` mentioned above could be helpful for others when investigating errors. Maybe I'll open a PR for the example.
